### PR TITLE
add option to flush inactive pages / trap exceptions

### PR DESCRIPTION
**Pull request by joequant**
This patch adds the ability to flush only inactive pages.  It also
attempts to flush changes for following files if there is an exception
in parsing one particular file.

Intended to provide diagnostics for nextcloud/documentserver_community#100

### CODE REVIEW

**Comment by kesselb** [comment]
> trap exceptions

Make sense.

> flush inactive pages

Mind to explain that change? I don't see how that adds diagnostics. If your intention is to run `occ documentserver:flush --inactive-pages` as cronjob then no from my point because it does not improve anything. Just another workaround to fix #100.

**Comment by joequant** [comment]
It's been reported that if you run occ documentserver:flush on a cron job, then you will eventually run into overwrites and conflicts.  Adding the --inactive flag skips that pages that are not supposed to be overwritten and so its a safer workaround.

**Comment by kesselb** [comment]
https://www.github.com/nextcloud/documentserver_community/tree/master/lib%2FBackgroundJob%2FCleanup.php

Writing back inactive documents is what the cleanup background job already does.

**Comment by joequant** [comment]
Right, but sometimes that job fails for whatever reason.  Adding an
--inactive flag forces the system to do the same
sync that the background process does, rather than doing a full flush which
might cause unexpected behavior.

**Comment by icewind1991** [comment]
Thanks!

**Pull request merged**
