### PR TITLE
Add nextcloud 28 support

### PR DESCRIPTION
**Pull request by WhoAmI0501**
Since no one else is doing it, i implemented some fixes for Nextcloud 28. Works on my machine.

May solves #310 and #306

Want to try it?
```console
sudo -i  # or su - root or whatever you need to do to become root on your box
apt update
apt install make cpio rpm2cpio curl git
cd /tmp
git clone https://github.com/WhoAmI0501/documentserver_community.git
cd documentserver_community
make
cd ..
tar cf documentserver_community.tar documentserver_community/3rdparty/ documentserver_community/appinfo/ documentserver_community/img/ documentserver_community/js/ documentserver_community/lib/ documentserver_community/README.md
cd /var/www/html/nextcloud/apps/  # or where-ever your nextcloud is installed
mv documentserver_community documentserver_community_old
tar xf /tmp/documentserver_community.tar
chown -R www-data:www-data documentserver_community  # or whatever user/group you're using
cd ..
sudo -u www-data php occ upgrade
```

### CODE REVIEW

**Comment by menschentier** [comment]
works perfectly - thank you!

**Comment by phillipp** [comment]
@icewind1991 Could you please merge the pull request?

**Comment by rsedlmeier** [comment]
Wounderful, it work.

1000 Thx
Cheers Roland

**Comment by chadek** [comment]
Sorry did not saw this before, it's been a while since I did not touch my nextcloud instance. Looks good to me, the only thing I see is that for nextcloud 28 support you only need to bump the version number right? You should then remove the user limit update from this pr to track real changes. Thanks for the contribution!

**Comment by WhoAmI0501** [comment]
Sorry for not responding anymore here, was quite busy. Thanks for your reaction and implementing the fix upstream. :)

**Pull request merged**
