### PR TITLE
Update info.xml

### PR DESCRIPTION
**Pull request by Kitanit**

### CODE REVIEW

**Comment by phonon112358** [comment]
closes #260 
The app is working fine with NC 24 and php 8.1, hence the max-version can be increased .

**Comment by Kitanit** [comment]
Maybe one of them should be mentioned.
Screenshot_20220528-215157_Brave

**Comment by Kitanit** [comment]
*Very sorry for the mass ping, but without it, this plugin will die.

@sonic1200 @joequant @jospoortvliet @evilJazz @Abijeet

**Comment by Kitanit** [comment]
> *Very sorry for the mass ping, but without it, this plugin will die.
> 
> @sonic1200 @joequant @jospoortvliet @evilJazz @Abijeet

@phonon112358 Do you know where else to "knock"?

**Comment by RoiArthurB** [comment]
@Kitanit Maybe it can be worth at the same time bumping the onlyoffice's docker image version to the latest 7.1? 🤔🤔🤔

Also, if no devs answer, maybe it'll need to be forked to keep it alive 😕😕

**Comment by Kitanit** [comment]
> Maybe it can be worth at the same time bumping the onlyoffice's docker image version to the latest 7.1? thinkingthinkingthinking
> 
> Also, if no devs answer, maybe it'll need to be forked to keep it alive confusedconfused

Personally, I did so by raising the docker office, and about the fork you need to think about because you need not just fork but add more to the nextcloud store and remove the old one if possible, because it is in fact already garbage

**Comment by RoiArthurB** [comment]
> Personally, I did so by raising the docker office

Me too, but you didn't commit it in this PR :)

>  and about the fork you need to think about because you need not just fork but add more to the nextcloud store and remove the old one if possible, because it is in fact already garbage

Well, to add it to the store, you just need to pick a new name to this plugin (like `documentserver_community_revival`), and, as nextcloud did abandon this, seeing the revival proposed on the store may remind them this one and either re-update it or simply remove it from the store. 
At least, that's how I see things and I think that, even if the two plugins exists, people will more easily go and pick the version compatible with their instance than the other one with plenty of bad review 🤔🤔🤔

**Comment by chadek** [comment]
The last time plugin was broken @icewind1991 fixed it (or at least merged the fix) I think this is where you want to knock @Kitanit

**Comment by chadek** [comment]
Well shall we then fork it? I would be really nice to have this stuff maintained and allow contributions to be merge

**Comment by g-work** [comment]
Are there any news? Community Document Server is basically the last thing keeping me from upgrading to NC 24.

**Comment by ml31415** [comment]
It's probably time to knock on the nextcloud doors and get some other maintainer(s) designated ...

**Comment by g-work** [comment]
Is there any established procedure how to deal with such a situation?

**Pull request closed without merging**
